### ISSUE TITLE
Supporting .css files, for use with @cypress/react?

### ISSUE THREAD

**Issue by ncknuna** [sod/cypress-esbuild-preprocessor#1]
This preprocessor is really awesome, thanks for building it! My build times went from 90s -> ~1s!

However, because of the way that esbuild handles CSS files, when I try to write component unit tests with Cypress using the @cypress/react (https://www.npmjs.com/package/@cypress/react , aka cypress-react-unit-test) package, the components I'm testing don't end up with their associated CSS files, so everything is unstyled. As someone who hasn't written a cypress plugin and is new to esbuild, I'm a bit lost as to how to make it work. Would you be open to adding CSS support for @cypress/react, or point me in the right direction so I can add it? Thanks!!

Minimal repro repo here: https://github.com/ncknuna/cypress-react-esbuild

**Comment by sod** [comment]
Sadly I don't have time right now, but if you wanna give it a try, the preprocesser is just a single file, see https://github.com/sod/cypress-esbuild-preprocessor/blob/master/src/index.ts. But the preprocessor doesn't touch your files at all, it's just the glue between cypress & esbuild. All the smarts right now is done by esbuild.

Maybe instead of using esbuild directly, we could use https://github.com/vitejs/vite instead. Vite also uses esbuild for typescript, but adds a hole lot to support much more of the frontend stack.

If it's already doable with esbuild (I don't know) the options are fully passed to the bundler, maybe there is something, like https://esbuild.github.io/api/#external or https://esbuild.github.io/content-types/#css

**Comment by sod** [comment]
Hm, maybe give https://github.com/evanw/esbuild/issues/20 an upvote :)

**Comment by ncknuna** [comment]
Ah, yea, I looked into the css processor, but it looks like it just takes all css imports and pulls them into a single css bundle, but doesn't actually inject that bundle into the header of the DOM (in webpack terms, it acts as the `css-loader`, but not the `style-loader`). I tried manually navigating to the path I would expect the css file to be at (which, according to the css content type, would be the same at the entrypoint name, but with `.css` as the extension) there wasn't anything there, so I'm at a bit of a loss. I'll see if the cypress folks can give me some direction

**Comment by ncknuna** [comment]
@sod , is this fixed now, or closing because it won't be fixed. No worries either way, I just wanted to know :)

**Comment by sod** [comment]
I don't have the usecase for it and thus no intention of implementing it.
